[project]
name = "address-validation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "geopy>=2.4.1",
    "pandas>=2.3.1",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]
